import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const config = {
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: "rebuild-notify",
			setup(build) {
				build.onEnd((result) => {
					const pluginFolder = path.join(
						process.env.VAULT_FOLDER,
						".obsidian/plugins/my-obsidian-plugin"
					);
					fs.writeFileSync(path.join(pluginFolder, ".hotreload"), "");

					for (const file of [
						"manifest.json",
						"main.js",
						"styles.css",
					]) {
						copyFiles(pluginFolder, file);
					}
				});
			},
		},
	],
};

const context = await esbuild.context(config);

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

async function copyFiles(dest, file) {
	const destFilePath = path.join(dest, file);

	if (!fs.existsSync(dest)) {
		fs.mkdirSync(dest, { recursive: true });
	}

	fs.copyFile(file, destFilePath, () =>
		console.log(`copy ${file} to ${destFilePath}`)
	);
}
